In [2]:
import numpy as np

In [3]:
a = [24,25,26,27,29,32,33,32,29,25,24]
a = np.array(a)

In [4]:
print(a)
type(a)

[24 25 26 27 29 32 33 32 29 25 24]


numpy.ndarray

In [5]:
b = a-4
b = b*2
print(b)

[40 42 44 46 50 56 58 56 50 42 40]


In [6]:
print(np.arange(10.4))
print(np.arange(0.5,10.4,0.8))
print(np.arange(12.04,12.84,0.08))
print(np.arange(0.5,10.4,0.8,int))


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]
[12.04 12.12 12.2  12.28 12.36 12.44 12.52 12.6  12.68 12.76 12.84]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
print(np.linspace(1,10,7,endpoint=False))
print(np.linspace(1,10,7,endpoint=True))


[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [8]:
a = np.array(12)
print(np.ndim(a))

0


In [9]:
O = np.array([1,2,3,4,5,6,7])
T = np.array([[1,2],[3,4]])
Th = np.array([[[1,2,3],[3,4,5]],
               [[5,6,7],[7,8,9]],
               [[1,2,3],[3,4,5]],
               [[5,6,7],[7,8,9]]])

In [10]:
print(O,T,Th,sep=f'\n\n')

[1 2 3 4 5 6 7]

[[1 2]
 [3 4]]

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]

 [[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


In [11]:
np.shape(O)

(7,)

In [12]:
np.shape(T)

(2, 2)

In [13]:
np.shape(Th)

(4, 2, 3)

In [14]:
np.shape(42)

()

In [15]:
k = np.array([1,2,3,4,90,5,7,6])
print(k[0])
print(k[-2])
print(k[-8])
print(k[-3:-1])

1
7
1
[5 7]


In [16]:
A = np.array([[3.4, 8.7, 9.9],
            [1.1, -7.8, -0.7],
            [4.1, 12.3, 4.8]])

In [17]:
print(A[0,1])
print(A[1])
print(A[1][0])



8.7
[ 1.1 -7.8 -0.7]
1.1


In [18]:
print(A)

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]


In [19]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

In [20]:
print(A[:3,2:])
print(A[3:,:])
print(A[:,4:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]
[[41 42 43 44 45]
 [51 52 53 54 55]]
[[15]
 [25]
 [35]
 [45]
 [55]]


In [21]:
X = np.arange(28).reshape(4, 7)
print(X)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [22]:
print(X[::2,::3])

[[ 0  3  6]
 [14 17 20]]


In [23]:
print(X[:,3::2])

[[ 3  5]
 [10 12]
 [17 19]
 [24 26]]


In [24]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
S = A[2:6]
S[0] = 22
S[1] = 23
print(A)

[ 0  1 22 23  4  5  6  7  8  9]


In [25]:
np.may_share_memory(S,A)

True

In [26]:
K = np.zeros((2,2),int)
L = np.ones((2,2),int)

In [27]:
print(K,L,sep='\n\n')

[[0 0]
 [0 0]]

[[1 1]
 [1 1]]


In [28]:
R = K - L

In [29]:
print(R)

[[-1 -1]
 [-1 -1]]


In [30]:
A = [[1,2,3,4],[5,6,7,8]]
A = np.array(A)

In [31]:
np.zeros_like(A)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
np.ones_like(A)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
np.empty((7,))

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [34]:
np.identity(4,int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
np.eye(4,5,k=0,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [36]:
#Exercises
#1
v = np.random.randint(0,25,size=10)
print(v)

#2
v_odd = v[1::2]
print(v_odd)

#3
k = v[::-1]
print(k)

#4
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

#5
m = np.linspace(0,20,num=20,endpoint=False).reshape((4,5))
print(m)

#9
cut = m[1:-1,1:-1]
print(cut)

#6
r = m[:,::-1]
print(r)

#7
rr = m[::-1,:]
print(rr)

#8
rrr = m[::-1,::-1]
print(rrr)

[20  3 19  3 19  1 22 23  7  0]
[ 3  3  1 23  0]
[ 0  7 23 22  1 19  3 19  3 20]
200
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
[[ 6.  7.  8.]
 [11. 12. 13.]]
[[ 4.  3.  2.  1.  0.]
 [ 9.  8.  7.  6.  5.]
 [14. 13. 12. 11. 10.]
 [19. 18. 17. 16. 15.]]
[[15. 16. 17. 18. 19.]
 [10. 11. 12. 13. 14.]
 [ 5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.]]
[[19. 18. 17. 16. 15.]
 [14. 13. 12. 11. 10.]
 [ 9.  8.  7.  6.  5.]
 [ 4.  3.  2.  1.  0.]]


In [37]:
#1 Exercise 
#Define a structured array with two columns. The first column contains the product ID, which can be defined as an int32. The second column shall contain the price for the product. How can you print out the column with the product IDs, the first row and the price for the third article of this structured array?

book = np.dtype([('Product ID', np.int32),('Price', np.float64)])

register = np.array([(1001,151.50),(1002, 99.95),(1003, 15.35),(1004, 34.45)],dtype=book)

#(i)
print(register['Product ID'])
print(register[0])
print(register[2]['Price'])


[1001 1002 1003 1004]
(1001, 151.5)
15.35


In [38]:
#2
#Figure out a data type definition for time records with entries for hours, minutes and seconds.

time = np.dtype([('hours',np.int8),('minutes',np.int8),('seconds',np.int8)])
timing = np.array([(12,30,45)],dtype=time)
print(timing[0]['minutes'])

30


In [39]:
K = np.array([12,44,23,27,75,92,43,79,56])
Kt = K+2
print(Kt)

[14 46 25 29 77 94 45 81 58]


In [40]:
A = np.array([[1,2,3],[4,5,6]])
O = np.ones_like(A)
A = A + O
print(A)

[[2 3 4]
 [5 6 7]]


In [41]:
O = O + O

In [42]:
print(O*A)

[[ 4  6  8]
 [10 12 14]]


In [43]:
M = np.array([[1,2,3],[4,5,6]])
N = np.array([[5,6],[7,8],[9,10]])
np.dot(M,N)

array([[ 46,  52],
       [109, 124]])

In [44]:
M = np.mat(M)
N = np.mat(N)

In [45]:
M*N

matrix([[ 46,  52],
        [109, 124]])

In [46]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A == B

array([[False, False],
       [False, False]])

In [47]:
np.array_equal(A,A)

True

In [48]:
a = np.array([[True,True],[False,False]])
b = np.array([[True,False],[True,False]])
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[[ True  True]
 [ True False]]
[[ True False]
 [False False]]


In [49]:
#Broadcasting
A = np.array([[11,12,13],[14,15,16],[17,18,19]])
B = np.array([1,2,3])
A * B

array([[11, 24, 39],
       [14, 30, 48],
       [17, 36, 57]])

In [50]:
print(np.array([[1,2,3],]*4))

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [51]:
g = np.array([1,2,3])
g[:,np.newaxis] * A

array([[11, 12, 13],
       [28, 30, 32],
       [51, 54, 57]])

In [52]:
A = [1,2,3],[4,5,6],[7,8,9],[10,11,12]
A = np.array(A)

In [53]:
A.flatten(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
A.flatten(order='F')

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [55]:
Z = np.arange(24)
Z.reshape((4,6))
np.reshape(Z,(8,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [56]:
H = np.arange(0,24).reshape((3,4,2))
L = np.arange(100,124).reshape((3,4,2))


In [57]:
np.concatenate((H,L))

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11],
        [ 12,  13],
        [ 14,  15]],

       [[ 16,  17],
        [ 18,  19],
        [ 20,  21],
        [ 22,  23]],

       [[100, 101],
        [102, 103],
        [104, 105],
        [106, 107]],

       [[108, 109],
        [110, 111],
        [112, 113],
        [114, 115]],

       [[116, 117],
        [118, 119],
        [120, 121],
        [122, 123]]])

In [58]:
np.concatenate((H,L),axis=1)

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [100, 101],
        [102, 103],
        [104, 105],
        [106, 107]],

       [[  8,   9],
        [ 10,  11],
        [ 12,  13],
        [ 14,  15],
        [108, 109],
        [110, 111],
        [112, 113],
        [114, 115]],

       [[ 16,  17],
        [ 18,  19],
        [ 20,  21],
        [ 22,  23],
        [116, 117],
        [118, 119],
        [120, 121],
        [122, 123]]])

In [59]:
np.concatenate((H,L),axis=2)

array([[[  0,   1, 100, 101],
        [  2,   3, 102, 103],
        [  4,   5, 104, 105],
        [  6,   7, 106, 107]],

       [[  8,   9, 108, 109],
        [ 10,  11, 110, 111],
        [ 12,  13, 112, 113],
        [ 14,  15, 114, 115]],

       [[ 16,  17, 116, 117],
        [ 18,  19, 118, 119],
        [ 20,  21, 120, 121],
        [ 22,  23, 122, 123]]])

In [60]:
d = np.array(range(12)).reshape((3,4))
j = np.array(range(12,24)).reshape((3,4))

In [61]:
print(d,j,sep='\n\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [62]:

np.concatenate((d,j),axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [63]:
np.concatenate((d,j))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
f = np.array([1,2,3])
g = np.array([4,5,6])
np.row_stack((f,g))

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.row_stack((f[:,np.newaxis],g[:,np.newaxis]))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [66]:
A = np.array([[1,2],[3,4]])
np.tile(A,(3,5))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])

In [67]:
np.tile(A,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [68]:
np.tile(A,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [69]:
A = np.array([1,2,3,4,5,6,7])

In [70]:
B = A[A>=5]

In [71]:
B

array([5, 6, 7])

In [72]:
print(A<5)

[ True  True  True  True False False False]


In [73]:
U = np.array([3,4,6,10,24,89,45,43,46,99,100])

In [74]:
print(U[(U%3!=0)])
print(U[U%5==0])
print(U[(U%5==0) & (U%3==0)])
U[U%3==0] = 42

[  4  10  89  43  46 100]
[ 10  45 100]
[45]


In [75]:
print(U)

[ 42   4  42  10  42  89  42  43  46  42 100]


In [76]:
numbers = np.arange(101)
is_prime = np.ones_like(numbers,dtype=bool)
is_prime[:2] = False
for i in range(2,10):
    if is_prime[i]:
        is_prime[i*i::i] = False

primes = numbers[is_prime]

In [77]:
primes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [86]:
#prime number program again for practice

numbers = np.arange(101)
is_prime = np.ones_like(numbers,dtype=bool)
is_prime[:2] = False
for i in range(2,int(np.sqrt(len(numbers)))):
    if is_prime[i]:
        is_prime[i*i::i] = False

prime = numbers[is_prime]

In [87]:
print(prime)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
